apiVersion: v1
kind: Service
metadata:
  name: masterdata
  labels:
    group: example
spec:
  selector:
    app: masterdata
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP