server:
  port: 8080

spring:
  application:
    name: mock-service

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true

mock:
  upload-path: files/paste.txt
  test-value: test