apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traffic-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/matsior/traffic.git
    targetRevision: HEAD
    path: kubernetes/mock-service
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true