apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-service
  labels:
    group: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mock-service
      layer: backend
  template:
    metadata:
      labels:
        app: mock-service
        layer: backend
    spec:
      containers:
        - name: mock-service
          image: matsior/mock-service:0.0.3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /files
              name: paste-volume
          env:
            - name: MOCK_TEST_VALUE
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: mock-test-value
      volumes:
        - name: paste-volume
          persistentVolumeClaim:
            claimName: host-pvc