apiVersion: v1
kind: Service
metadata:
  name: mock-service
  labels:
    group: example
spec:
  selector:
    app: mock-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer