apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mock-service
      layer: backend
  template:
    metadata:
      labels:
        app: mock-service
        layer: backend
    spec:
      containers:
        - name: mock-service
          image: matsior/mock-service:0.0.1