apiVersion: v1
kind: Service
metadata:
  name: mock-service
  labels:
    group: example
spec:
  selector:
    app: mock-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-service
  labels:
    group: example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mock-service
      layer: backend
  template:
    metadata:
      labels:
        app: mock-service
        layer: backend
    spec:
      containers:
        - name: mock-service
          image: matsior/mock-service:0.0.3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /files
              name: paste-volume
          env:
            - name: MOCK_TEST_VALUE
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: mock-test-value
      volumes:
        - name: paste-volume
          persistentVolumeClaim:
            claimName: host-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-store-env
data:
  mock-test-value: k8s-config-map
