apiVersion: v1
kind: Service
metadata:
  name: mock-service
  labels:
    group: example
spec:
  selector:
    app: mock-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-service
  labels:
    group: example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mock-service
      layer: backend
  template:
    metadata:
      labels:
        app: mock-service
        layer: backend
    spec:
      containers:
        - name: mock-service
          image: matsior/mock-service:0.0.1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
